import streamlit as st
import torch
import torch.nn.functional as F
from PIL import Image
from torchvision import transforms
import torchvision.datasets as datasets
import os
from model_architecture import CNN 
from getFood import load_food_base

@st.cache_data
def load_classes():
    with open("classes.txt", "r") as f:
        # line.strip() removes whitespace and newlines; the 'if line.strip()' condition skips empty lines
        classes = [line.strip().replace("_", " ").title() for line in f.readlines() if line.strip()]
    return classes

food_classes = load_classes()
food_database = load_food_base()
# Streamlit interface
st.set_page_config(page_title="Food Detector")
@st.cache_resource
def load_model():
    # Initialize the CNN model
    model = CNN()
    # Load weights generated by the training script
    # Choose the device (use CUDA if available, otherwise CPU)
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    state_dict = torch.load("best_model.pth", map_location=device)
    model.load_state_dict(state_dict)
    model.to(device)
    model.eval() # Evaluation mode



    return model

# Data preprocessing
preprocess = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# Web page
st.title("Food Recognition")
st.markdown("Upload an image.")

file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if file is not None:
    # Display the user's image
    img = Image.open(file).convert('RGB')
    st.image(img, caption="Uploaded image", use_container_width=True)

    if st.button("Analyze dish"):
        with st.spinner("The network is processing the image..."):
            # 1. Load the model
            net = load_model()
            
            # 2. Prepare the image
            img_tensor = preprocess(img).unsqueeze(0) 
            # Move the tensor to the same device as the model
            device = next(net.parameters()).device
            img_tensor = img_tensor.to(device)
            
            # 3. Prediction
            with torch.no_grad():
                outputs = net(img_tensor)
                probabilities = F.softmax(outputs, dim=1)
                prob, index = torch.max(probabilities, 1)

            # 4. Display results
            class_id = index.item()
            confidence = prob.item() * 100  
            food_data = None
            display_name = f"Unknown dish ID: {class_id}"

            try:
                potrawa_name = food_classes[class_id]
            except IndexError:
                potrawa_name = f"Unknown dish, ID: {class_id}"

            if class_id < len(food_classes):
                food_key = food_classes[class_id].lower().replace(" ", "_") # e.g. "pizza"
                display_name = food_key.replace("_", " ").title() # e.g. "Pizza"
                
                # Fetch the object from the database (the key is the lowercase folder name, e.g. "pizza")
                food_data = food_database.get(food_key.lower())
                if food_data is None:
                    food_data = food_database.get(food_key) 
                if food_data is None:
                    food_data = food_database.get(food_key.replace("_", " ").lower())

            st.success(f"### Result: {potrawa_name}")
            st.metric("Model confidence", f"{confidence:.2f}%")
            
            st.info(f"We prepared a recipe for {potrawa_name}; it will appear here.")

            if food_data is not None:
                st.markdown("---")
                st.subheader("Nutritional values (per serving)")
                
                col1, col2, col3, col4 = st.columns(4)
                col1.metric("Calories", f"{food_data.getKcal()} kcal")
                col2.metric("Protein", f"{food_data.getProtein()}g")
                col3.metric("Carbohydrates", f"{food_data.getCarbs()}g")
                col4.metric("Fats", f"{food_data.getFat()}g")
                
                st.markdown("---")
                st.subheader(f"📖 Recipe for {potrawa_name}")
                
                # We use the method with the typo from the original code: getReceipe()
                recipe_text = food_data.getReceipe()
                if recipe_text:
                    st.write(recipe_text)
                else:
                    st.info("No recipe description is available in the database for this dish.")
            else:
                st.warning(f"The key '{food_classes[class_id]}' was recognized, but detailed data is not available :(.")

st.sidebar.markdown("### Model Statistics")
st.sidebar.text("Architecture: Custom CNN")
st.sidebar.text("Number of parameters: ~8.4 million")
st.sidebar.text("Target RF: 158")


